### ISSUE TITLE
Installations Instructions relying on SSH

### ISSUE THREAD

**Issue by iliassarbout** [Eyened/retinalysis-inference#1]
Hello,
I noticed that the clone instructions in the README rely on SSH for cloning the repositories:

git clone git@github.com:Eyened/retinalysis-fundusprep.git rtnls_fundusprep

In environments where SSH is blocked or not permitted, users may encounter issues cloning the repository. I suggest updating the instructions to include the HTTPS method as an alternative:

git clone https://github.com/Eyened/retinalysis-fundusprep.git rtnls_fundusprep
git clone https://github.com/Eyened/retinalysis-inference.git rtnls_inference

This change would help ensure that users in restricted networks can still easily clone the repositories and contribute to the project.

Thank you for considering this update,

Respectfully,
Ilias Sarbout

**Comment by josedvq** [comment]
Thanks for the suggestion! I have applied these changes.
