### ISSUE TITLE
No hyperlink to model weights

### ISSUE THREAD

**Issue by iliassarbout** [Eyened/retinalysis-inference#2]
Hello,

There are currently no instructions on how to download model weights to run the inference notebook at retinalysis-inference/tree/main/notebooks/inference.ipynb. These instructions are currently given in a separate github repository (vascx).

Thank you for considering this issue,

Respectfully,
Ilias

**Comment by josedvq** [comment]
Hello, thanks! I have pushed a change that pulls vascx models from our huggingface repository and updated the README.
Please reinstall or manually install huggingface-hub==0.25.1
This repository is generic and will be used for models other than vascx, so we will keep the notebook showing how to run all the vascx models in its own repository.
